name: CI/CD Pipeline

on:
  push:
    branches:
      - backend
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # 确认这是兼容 Node.js 20 的最新版本

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2 # 确认这是兼容 Node.js 20 的最新版本

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # 确认这是兼容 Node.js 20 的最新版本

      - name: Login to Docker Hub
        uses: docker/login-action@v2 # 确认这是兼容 Node.js 20 的最新版本
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v3 # 确认这是兼容 Node.js 20 的最新版本
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: s68543/gang_du_pos_backend:latest
          platforms: linux/amd64
          progress: plain

      - name: SSH into Linode and deploy
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }} << EOF
            docker image prune -f
            docker compose -f docker_compose.yml down
            docker compose -f docker_compose.yml pull 
            docker compose -f docker_compose.yml up --build -d
          EOF
